---
all:
  vars:
    ansible_user: test
    ansible_ssh_pass: test

  children:
    prod:
      hosts:
        agent1:
    staging:
      hosts:
        agent2:
        agent3:

ungrouped:
  hosts:
    localhost
  vars:
    ansible_connection: local
