- name: Update all system
  hosts: all
  become: yes
  tasks:
    - name: Update repository cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Upgrade packages
      apt: upgrade=dist force_apt_get=yes